### PR TITLE
V2 rewrite

### LINKED ISSUE #73: Am I correct that the root type can only be object?
## What did you do

I used `type: 'array'` at the root of my json schema file.

## What did you expect to happen

I expected it to be documented.

## What happened

nothing related to type `array` was documented.

## What's your environment

* Operating System: Mac OS X El Capitan
* node.js version: `v9.4.0`

## Do you have example files:

For this schema
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "http://www.axa.ch/schemas/types/children.json",

  "type": "array",
  "title": "Children",
  "description": "Components rendered within a Component.",

  "additionalItems": false,
  "items": [
    { "$ref": "http://www.axa.ch/schemas/components/Autocomplete.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/BulletRadioButtons.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/Button.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/Checkbox.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/Datepicker.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/Dropdown.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/Error.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/Icon.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/Link.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/List.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/ListItem.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/Map.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/Markdown.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/ModalDialog.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/MultipleSelectList.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/MultipleSelectListItem.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/ProcessEnding.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/SegmentedRadioButtons.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/SelectList.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/SelectListItem.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/Textarea.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/Textfield.json#" },
    { "$ref": "http://www.axa.ch/schemas/components/Typo.json#" }
  ]
}
```

I'm getting following Markdown

```markdown
# Children Schema

```
http://www.axa.ch/schemas/types/children.json
```

Components rendered within a Component.

| Abstract | Extensible | Status | Identifiable | Custom Properties | Additional Properties | Defined In |
|----------|------------|--------|--------------|-------------------|-----------------------|------------|
| Can be instantiated | No | Experimental | No | Forbidden | Permitted | [types/children.json](types/children.json) |
```

### LINKED ISSUE #125: Change directory layout to enable separate output files for nested objects?
Right now, we have a setup that creates one MD file for every schema file. While this makes it easy to map between input and output, it also forces schema authors to adjust their schemas to the quirks of the tool/constraints of the markdown format (e.g. maximum depth mapping)

I've been thinking that we might fare better with following approach:

- each `type: object` schema in the entire list of schemas creates an output file
- we use the `$id` and JSON Path to to sub-schema to define the file name (probably with a hash or globbing)
- we never embed or nest object schemas, but always link

As this would be a breaking change, I'd like to get your feedback first.

### PR DESCRIPTION
**Pull request by trieloff**
This is still a work in progress of what will become an effective re-write of `jsonschema2md`

Some of the changes that are coming:

- `optimist` (unmaintained) replaced with `yargs`
- `bluebird`, `lodash` replaced with `ferrum`
- `i18n` (with unmaintained dependencies) replaced with `es2015-i18n-tag`
- replaced `ejs` templates with `mast-builder` (#126 and #174)
- root schemas can be of any type now (fixes #73 and #72)
- support for "join types" with `anyOf`, `oneOf`, `allOf`, and `not` (#94 and #52 and #20)
- schemas can be nested up to any level you'd like (an array of objects within an array of objects within…) fixes #125
- better support for type arrays #177 
- schemas are no longer validated

Some things will be made easier with the change:
- #118 
- #34

And some things will be made impossible:
- #123 

but this is still work in progress and a couple of things remain to be done:

- [x] replace `jasmine` with `mocha` and measure code coverage
- [x] bring code coverage up to 100%
- [x] support `additionalProperties` #95
- [x] support `additionalItems` #31 
- [x] support `patternProperties` #180 
- [x] provide German translation (`en` is default locale)
- [x] create JSON schema output

### CODE REVIEW

**Comment by Relequestual** [comment]
What's meant by "schemas are no longer validated"?
Is this in relation to #100 ?

**Comment by trieloff** [comment]
We used to have a dependency to `ajv` and used `ajv` to validate the schemas before we would even try to generate documentation. This brought a couple of drawbacks like:
- additional dependencies
- additional processing time
- you needed to specify the JSON Schema version you were using

for very little benefit.

In order to implement #100 and generate the list of supported and unsupported keywords (https://github.com/adobe/jsonschema2md/blob/master/schemasupport.md) I've tagged every use of a keyword in the code with `keyword` and wrote a test that compares the keywords that have been used against the keywords that are mentioned in the spec. This does not rely on schema validation at all.

**Comment by Relequestual** [comment]
I hadn't realised you had made the jump to draft 2019-09! Very exciting!
From previous discussions and this, I think what you've developed would be a great candidate for creating a vocabulary.
Obviously it's a little tricky to create and test out addtional vocabulaires with so few implementations, but they will come. =]
You have my email. Feel free to reach out should you want any feedback or sounding board for ideas!

**Pull request merged**
