### PR TITLE
fix: Definition object, definitions based on the property list structure

### PR DESCRIPTION
**Pull request by alainlecluse**
#228
fix: Definition object, definitions based on the property list structure

### CODE REVIEW

**Comment by trieloff** [comment]
What's the reason for removing the table?

**Comment by alainlecluse** [comment]
What I noticed was that the definitions only worked for objects.
So if a definition element is not an object, the group table was always empty, and no relevant information was provided for the definition. 

My initial start was to make the group table and property list conditional based on the type. And add a `maketypefact` section a link for more information. 

Before committing that solution, I've concluded that it deviated too much from how the property section is constructed. 
It is resulting in the combination of the reference block and the parts from a normale property.

**Comment by trieloff** [comment]
@alainlecluse can you confirm that you signed the CLA?

**Comment by alainlecluse** [comment]
@trieloff Yes, I did. 
I do not know why it keeps saying I did not

**Pull request merged**
