### PR TITLE
Issue #117: Add blank lines for proper HTML rendering with kramdown

### PR DESCRIPTION
**Pull request by fmeschbe**
Proposed changes to fix issue #117.

### CODE REVIEW

**Comment by fmeschbe** [comment]
Missed updating/fixing the text cases. Working on it.

**Comment by fmeschbe** [comment]
Updated the comparison sources now the tests succeed.

**Comment by anjankaur** [comment]
@trieloff  Sorry, I forgot about semantic-release here. And merged before rewriting with npm run commit.

**Pull request merged**
