### PR TITLE
fix(schemaProxy.js): fix resolving $refs that are file references - #92

### LINKED ISSUE #92: unresolved reference when using relative $ref
## What did you do

I tried generated markdown from a schema that makes use of relative definitions that are all in one file.

```sh
jsonschema2md -d ./schema.json
```

Splitting these references out into separate files with absolute URL's does work, but it makes the schema far less portable.

## What did you expect to happen

Successfully generate markdown without any errors.

## What happened

```sh
07
info: output directory: /Users/wayneberry/src/github.com/overhq/open-file-format-specification/out
schema /Users/wayneberry/src/github.com/overhq/open-file-format-specification/schema.json has no $id
info: finished reading /Users/wayneberry/src/github.com/overhq/open-file-format-specification/schema.json, beginning processing....
/Users/wayneberry/src/github.com/overhq/open-file-format-specification/schema.json
unresolved reference: #/definitions/Identifier
unresolved reference: #/definitions/Identifier
Output processed.
info: Processing complete.
```

## What's your environment

* Operating System: `macOS 10.14.1`
* node.js version: `v11.2.0`

## Do you have example files:

For this schema

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/Project",
    "definitions": {
        "Project": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "identifier": {
                    "$ref": "#/definitions/Identifier"
                }
            },
            "required": [
                "identifier",
                "layers",
                "size"
            ],
            "title": "Project"
        },
        "Identifier": {
            "type": "string",
            "minLength": 36,
            "maxLength": 36,
            "examples": [
                "1467103b-45d3-49fa-addc-374370f93e9c"
            ],
            "description": "A universally unique identifier as specified by https://www.ietf.org/rfc/rfc4122.txt"
        }
    }
}
```

I'm getting following Markdown

```markdown
#  Schema

```
```


| Abstract | Extensible | Status | Identifiable | Custom Properties | Additional Properties | Defined In |
|----------|------------|--------|--------------|-------------------|-----------------------|------------|
| Cannot be instantiated | Yes | Experimental | No | Forbidden | Permitted |  |

#  Definitions

| Property | Type | Group |
|----------|------|-------|
| [identifier](#identifier) | reference | `#/definitions/Project` |

## identifier


`identifier`

* is optional
* type: reference
* defined in this schema

### identifier Type


* []() – `#/definitions/Identifier`
```

### PR DESCRIPTION
**Pull request by teq0**
As per JSON Schema docs, a $ref is a URI-reference that can be a full URI, such as an id, or a
relative reference, such as a file name. This adds the ability to resolves $refs that reference
local/relative files.

fix #92

### CODE REVIEW

**Comment by teq0** [comment]
I updated the docs that were affected by the change but left everything else as it was, even though they don't match the content generated with the current version as per https://github.com/adobe/jsonschema2md/issues/260.

**Comment by trieloff** [comment]
Thanks @teq0 I'll review on Monday.

**Review by trieloff — APPROVED** [review]

**Pull request merged**
