### PR TITLE
i18n is now used in all templates

### PR DESCRIPTION
**Pull request by Claymore1337**
Issue: #143

-Added i18n-node as dependency
-Add "i" as console arg and pass all args to the markdown.js.
-Add a translation file and use it in all templates.

A possible todo could be to add a linting rule which did not allow to use plain text in .ejs files

### CODE REVIEW

**Comment by Claymore1337** [comment]
I saw the 

> Commit Message Format

block to late and my message is wrong. Is there a way to fix it over git commit --amend ?

**Comment by trieloff** [comment]
@Claymore1337 no big deal, I can squash the commit.

**Comment by trieloff** [comment]
Looks good so far, but some of the tests are still failing.

**Comment by Claymore1337** [comment]
@trieloff 
Could you give me a hint  what excatly go wrong here? Cause there is nothing marked on the output

image

And is there a possibility to run the test on windows correctly?

**Comment by trieloff** [comment]
Looks like some whitespace issue. You could try to copy the offending file from the "actual" folder into the "expected" folder.

I haven't looked into Windows, but could set up a CI task for that.

**Comment by Claymore1337** [comment]
@trieloff 
I finally found the error. Sorry that this took so long :smile:

**Pull request merged**
