### PR TITLE
fix: moved definitions to bottom of output file

### PR DESCRIPTION
**Pull request by alainlecluse**
#226 Relocate definitons

Move the definition section to the bottom of output file.

### CODE REVIEW

**Comment by trieloff** [comment]
Hey, @alainlecluse – this looks good. Can you make sure to sign the Adobe CLA here http://opensource.adobe.com/cla.html so that the powers that be will let me merge. 

Thank you!

**Comment by alainlecluse** [comment]
@trieloff I saw the bot message and signed it right away for my GitHub account. But I noticed that the commit was done with a other email address. Don't know if that interferes. 

If needed I can redo the PR with a commit from the same email address as the GitHub account

**Comment by trieloff** [comment]
Thank you, that works for me. Your fix will be in the next release, which I expect in the next few minutes.

**Pull request merged**
