### PR TITLE
Add Dutch translations

### PR DESCRIPTION
**Pull request by tombrouwer**
This PR has no issue. I'm making a PR (this one) to fix the issue I'm having. I want to try your great work in Dutch.

I made the translations with GitLocalize.

### CODE REVIEW

**Comment by trieloff** [comment]
Hi @tombrouwer this looks good. As noted in the checks, we need you to sign the Adobe CLA http://opensource.adobe.com/cla.html before I can merge this (technically, before I can even review this)

**Comment by tombrouwer** [comment]
Hi @trieloff, I signed the CLA a few seconds ago. I do not know how to restart the check.

**Comment by trieloff** [comment]
Thanks, I'll check why the build isn't passing and (hopefully) merge this.

**Pull request merged**
