### PR TITLE
fix(traverseschema.js): skip generating files for certain keywords in…

### PR DESCRIPTION
**Pull request by togmund**
… the schema

When traversing the schemas, some objects and arrays are misinterpreted as schemas to be documented
rather than as generic structures used to define the schemas. Namely: 'examples', 'required', and
'properties'. Including these structures in the loadedschemas list generates a number of extranious
files with little value to the generated documentation.

BREAKING CHANGE: The extranious files, if they have some other value, will not be generated and
there is no mechanism to continue to g

Please mention the issue #… in the pull request.

Please remember to follow the documented [commit process](https://github.com/adobe/jsonschema2md/blob/master/Contributing.md#commit-message-format), specifcally commit using `npm run commit` which will construct the commit template required for automated semantic releases.

### CODE REVIEW

**Comment by trieloff** [comment]
Hi @togmund – this sounds like a great addition, and one that is long overdue. We had a number of bugs related to possible conflicts between keywords and identifiers. Please note that you need to sign the Adobe CLA so that I can review and merge the PR when it is ready.

**Comment by togmund** [comment]
Hey @trieloff! I've got a little more diligence I'm going to do on this PR, but I'll be sure to sign the CLA and mark as ready for review once I'm done. Thanks!

**Comment by togmund** [comment]
@trieloff 
Hey! I've taken another pass at it and am mostly happy, it covers the set of keywords I was personally bumping up against the most for extraneous files.
Tests updated too.
For reviewer sanity I have not regenerated the docs with the changes.
Thanks for taking a look!

**Review by trieloff — APPROVED** [review]
Looks good, sorry it took so long to get to it.

**Pull request merged**
