### PR TITLE
docs(readme): fix example of `-p` parameter

### PR DESCRIPTION
**Pull request by eNeRGy164**
No issue created, just a small fix in the example in readme.

### CODE REVIEW

**Comment by eNeRGy164** [comment]
Hi @trieloff, can you comment if there is work left that prevents this from being merged?

**Comment by trieloff** [comment]
Hi @eNeRGy164 – there wasn't, I just got behind with my workload. Thanks for the contribution.

**Comment by eNeRGy164** [comment]
Thanks!

**Pull request merged**
