### PR TITLE
fixed broken readme links

### LINKED ISSUE #74: Generated links in Readme.md are broken 404
## What did you do

I generated a markdown documentation by:

jsonschema2md -o docs/ -d schemas/ -e json

## What did you expect to happen

All linked schema within the `Readme.md` should point to correct URL.
For Example at https://github.com/axa-ch/aletheia/tree/develop/docs I expect correct link for:
- Autocomplete as https://github.com/axa-ch/aletheia/blob/develop/docs/components/Autocomplete.md but get instead https://github.com/axa-ch/aletheia/blob/develop/docs/components/Autocomplete.json.schema.md

## What happened

Instead all point to non-existent files and lead to `404` HTTP errors.

Wrongs urls like https://github.com/axa-ch/aletheia/blob/develop/docs/components/Autocomplete.json.schema.md

## What's your environment

* Operating System: Mac OS X El Capitan
* node.js version: `v9.4.0`

## Do you have example files:

Sure, all of https://github.com/axa-ch/aletheia/tree/develop/schemas aren't linked correctly.

I'm getting following Markdown

```markdown


 # Readme



## /

* [Aletheia API Schema](./api-schema.json.schema.md) – `http://www.axa.ch/schemas/api-schema.json` (Unknown)
* [BPM Data](./bpmData.json.schema.md) – `http://www.axa.ch/schemas/bpmData.json` (Unknown)
* [Error](./error.json.schema.md) – `http://www.axa.ch/schemas/error.json` (Unknown)
* [Schema](./schema.json.schema.md) – `http://www.axa.ch/schemas/schema.json` (Unknown)

## /components/

* [Autocomplete](./components/Autocomplete.json.schema.md) – `http://www.axa.ch/schemas/components/Autocomplete.json` (Unknown)
* [BulletRadioButtons](./components/BulletRadioButtons.json.schema.md) – `http://www.axa.ch/schemas/components/BulletRadioButtons.json` (Unknown)
* [Button](./components/Button.json.schema.md) – `http://www.axa.ch/schemas/components/Button.json` (Unknown)
* [Checkbox](./components/Checkbox.json.schema.md) – `http://www.axa.ch/schemas/components/Checkbox.json` (Unknown)
* [Datepicker](./components/Datepicker.json.schema.md) – `http://www.axa.ch/schemas/components/Datepicker.json` (Unknown)
* [Dropdown](./components/Dropdown.json.schema.md) – `http://www.axa.ch/schemas/components/Dropdown.json` (Unknown)
* [Error](./components/Error.json.schema.md) – `http://www.axa.ch/schemas/components/Error.json` (Unknown)
* [Icon](./components/Icon.json.schema.md) – `http://www.axa.ch/schemas/components/Icon.json` (Unknown)
* [Link](./components/Link.json.schema.md) – `http://www.axa.ch/schemas/components/Link.json` (Unknown)
* [List](./components/List.json.schema.md) – `http://www.axa.ch/schemas/components/List.json` (Unknown)
* [ListItem](./components/ListItem.json.schema.md) – `http://www.axa.ch/schemas/components/ListItem.json` (Unknown)
* [Map](./components/Map.json.schema.md) – `http://www.axa.ch/schemas/components/Map.json` (Unknown)
* [Markdown](./components/Markdown.json.schema.md) – `http://www.axa.ch/schemas/components/Markdown.json` (Unknown)
* [ModalDialog](./components/ModalDialog.json.schema.md) – `http://www.axa.ch/schemas/components/ModalDialog.json` (Unknown)
* [MultipleSelectList](./components/MultipleSelectList.json.schema.md) – `http://www.axa.ch/schemas/components/MultipleSelectList.json` (Unknown)
* [MultipleSelectListItem](./components/MultipleSelectListItem.json.schema.md) – `http://www.axa.ch/schemas/components/MultipleSelectListItem.json` (Unknown)
* [ProcessEnding](./components/ProcessEnding.json.schema.md) – `http://www.axa.ch/schemas/components/ProcessEnding.json` (Unknown)
* [SegmentedRadioButtonItem](./components/SegmentedRadioButtonsItem.json.schema.md) – `http://www.axa.ch/schemas/components/SegmentedRadioButtonItem.json` (Unknown)
* [SegmentedRadioButtons](./components/SegmentedRadioButtons.json.schema.md) – `http://www.axa.ch/schemas/components/SegmentedRadioButtons.json` (Unknown)
* [SelectList](./components/SelectList.json.schema.md) – `http://www.axa.ch/schemas/components/SelectList.json` (Unknown)
* [SelectListItem](./components/SelectListItem.json.schema.md) – `http://www.axa.ch/schemas/components/SelectListItem.json` (Unknown)
* [Textarea](./components/Textarea.json.schema.md) – `http://www.axa.ch/schemas/components/Textarea.json` (Unknown)
* [Textfield](./components/Textfield.json.schema.md) – `http://www.axa.ch/schemas/components/Textfield.json` (Unknown)
* [Typo](./components/Typo.json.schema.md) – `http://www.axa.ch/schemas/components/Typo.json` (Unknown)
* [Wizard](./components/Wizard.json.schema.md) – `http://www.axa.ch/schemas/components/Wizard.json` (Unknown)

## /validators/

* [Confirmation Validator](./validators/confirmation.json.schema.md) – `http://www.axa.ch/schemas/validators/confirmation.json` (Unknown)
* [Email Validator](./validators/email.json.schema.md) – `http://www.axa.ch/schemas/validators/email.json` (Unknown)
* [Format Validator](./validators/format.json.schema.md) – `http://www.axa.ch/schemas/validators/format.json` (Unknown)
* [Length Validator](./validators/length.json.schema.md) – `http://www.axa.ch/schemas/validators/length.json` (Unknown)
* [Required Validator](./validators/required.json.schema.md) – `http://www.axa.ch/schemas/validators/required.json` (Unknown)

## /types/

* [BPMID](./types/bpmid.json.schema.md) – `http://www.axa.ch/schemas/types/bpmid.json` (Unknown)
* [Children](./types/children.json.schema.md) – `http://www.axa.ch/schemas/types/children.json` (Unknown)
* [Component](./types/component.json.schema.md) – `http://www.axa.ch/schemas/types/component.json` (Unknown)
* [Controls](./types/controls.json.schema.md) – `http://www.axa.ch/schemas/types/controls.json` (Unknown)
* [Error Message](./types/msg.json.schema.md) – `http://www.axa.ch/schemas/types/msg.json` (Unknown)
* [Event](./types/event.json.schema.md) – `http://www.axa.ch/schemas/types/event.json` (Unknown)
* [Page values](./types/pageValues.json.schema.md) – `http://www.axa.ch/schemas/types/pageValues.json` (Unknown)
```

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #74

### CODE REVIEW

**Comment by trieloff** [comment]
@AndyOGo thanks for the PR – could you take a look at the failed build? I think all you need to do is to update the `README.md` in `specs`, so that it has the links you expect.

**Comment by AndyOGo** [comment]
@trieloff 
Sure I will look into it

**Comment by AndyOGo** [comment]
@trieloff 
I fixed the broken reade links for `example`.
Issue was caused within `relativePath` helper function - which replaces `schema` too.

**Comment by AndyOGo** [comment]
@trieloff 
@anjankaur 
Hope I provided all you need for it to be merged and released:)

**Comment by anjankaur** [comment]
@AndyOGo thanks for this, I merged it.

**Pull request merged**
