### PR TITLE
Implements #67.  Add an else clause to allow a nested object property

### PR DESCRIPTION
**Pull request by kmp1**
I also had issue #67 and it seems like it's a simple thing to fix (I can totally be wrong here, since I'm just idly perusing this code base) - I added an else clause to the nested-property template to allow objects to pass through (copying the one from array, because I don't know what I'm doing) and it seemed to resolve the issue.

### CODE REVIEW

**Comment by kmp1** [comment]
I've added the example I used which is the one from the original issue slightly modified - it's in `examples/schemas/nestedobj.schema.json`

**Comment by mshaposhnik** [comment]
Can someone merge this, please? Because object desctibed in another object still fails.

**Comment by mshaposhnik** [comment]
@trieloff something still blocking from merge ?

**Comment by trieloff** [comment]
- the existing tests are breaking
- there is no test that covers the change/use case

**Comment by eddyoc** [comment]
Any update on this?

**Comment by trieloff** [comment]
@eddyoc if you have tests in your private patch, I'd love to include them in this PR and get it merged, but we need to make sure it's compatible with existing tests (failing right now) and also tested in it's own right.

**Comment by mshaposhnik** [comment]
:+1:

**Comment by mshaposhnik** [comment]
It's time for 1.1.1 :)

**Pull request merged**
